export const uiText = {
  appShell: {
    specNavigation: "Specナビゲーション",
    commentSidebar: "コメントサイドバー",
  },
  leftNavigation: {
    open: "仕様一覧を開く",
    close: "仕様一覧を閉じる",
    resize: "仕様一覧の幅を変更",
    list: "仕様一覧",
    currentSpec: "現在の仕様",
  },
  sidebar: {
    comments: "コメント",
    close: "サイドバーを閉じる",
    reopen: "サイドバーを開く",
    resize: "サイドバー幅を変更",
    description: "現在のファイルのレビューコメント",
    counts: "コメント件数",
    filters: "コメントフィルター",
    moreActions: "その他",
    exports: "エクスポート",
    empty: "コメントはまだありません",
    emptyDescription:
      "このファイルの未解決・解決済みコメントがここに表示されます。",
    addHint: "Markdown本文の行にあるコメントボタンから追加できます。",
    idleTitle: "Specファイルを選択",
    idleDescription:
      "ワークスペース、Spec、ファイルを選択するとコメントが表示されます。",
    loading: "コメントを読み込み中",
    unavailable: "コメントを読み込めません",
    retry: "再試行",
    search: "コメント検索",
    searchPlaceholder: "本文、ファイル、抜粋、状態",
    clearSearch: "コメント検索をクリア",
    searchable: "検索対象",
    noSearchResults: "に一致するコメントはありません。",
    noFilterResults: "フィルターに一致するコメントはありません。",
    openFilter: "未解決",
    resolved: "解決済み",
    all: "すべて",
    moved: "移動",
    fuzzy: "曖昧",
    stale: "古い",
    orphaned: "位置不明",
    anchorsSuffix: "アンカー",
    noOpenComments: "未解決コメントはありません",
    noResolvedComments: "解決済みコメントはありません",
    saving: "保存中",
    copying: "コピー中",
    file: "ファイル",
    spec: "Spec",
    workspace: "ワークスペース",
    exportFileComments: "このファイルのコメントを書き出す",
    exportSpecComments: "この仕様のコメントを書き出す",
    exportWorkspaceComments: "ワークスペースのコメントを書き出す",
    copyPrompt: "AI用プロンプトをコピー",
    prompt: "AI用プロンプト",
    mcpFeedback: "MCP Feedback",
    applyAi: "AI適用",
    applyAiLabel: "コメントをAIで適用",
    applyAiPlaceholder:
      "AI用プロンプトのコピーは利用できます。AI適用はprovider連携で差分プレビューを生成できるようになってから有効になります。Markdownの書き込みには明示的な確認が必要です。",
  },
  commentThread: {
    edit: "コメントを編集",
    resolve: "解決する",
    reopen: "再オープン",
    delete: "削除",
    save: "保存",
    cancel: "キャンセル",
    body: "本文",
    bodyLabel: "コメント本文",
    emptyBody: "コメント本文を入力してください。",
    select: "コメントを選択",
    actions: "コメント操作",
    anchorDetails: "アンカー詳細",
    block: "ブロック",
    chars: "文字",
    confirmDelete: "このコメントを完全に削除しますか？",
    confirmDeleteAction: "コメント削除を確定",
    cancelDeleteAction: "コメント削除をキャンセル",
    created: "作成",
    updated: "更新",
    anchorMoved: "アンカー移動",
    fuzzyAnchor: "曖昧なアンカー",
    anchorOrphaned: "位置不明アンカー",
    anchorStale: "古いアンカー",
  },
  workspace: {
    controls: "ワークスペース操作",
    path: "ワークスペースパス",
    theme: "テーマ",
    themeMode: "テーマモード",
    system: "システム",
    light: "ライト",
    dark: "ダーク",
    openFolder: "ワークスペースフォルダを開く",
    load: "読み込む",
    loading: "読み込み中",
    opening: "開いています",
    switcher: "ワークスペース",
    sidebarList: "ワークスペース一覧",
    saved: "保存済みワークスペース",
    currentWorkspace: "現在のワークスペース",
    recent: "保存済みワークスペース",
    recentShort: "保存済み",
    noRecent: "保存済みワークスペースはありません",
    removeRecent: "一覧から削除",
    clearRecent: "保存済みをすべて削除",
    refresh: "現在の表示を再読み込み",
    reset: "リセット",
    openingPicker: "ワークスペース選択を開いています",
    loadingWorkspace: "ワークスペースを読み込み中",
    noWorkspace: "ワークスペースが選択されていません",
    openTitle: "ワークスペースを開く",
    openDescription:
      "対応しているSpecワークスペースフォルダを選択またはドロップしてMarkdownを読み込みます。",
  },
  specTree: {
    noWorkspaceTitle: "ワークスペース未選択",
    noWorkspaceDescription:
      "ワークスペースを読み込むと利用可能なSpecが表示されます。",
    specs: "Specs",
    loading: "Specファイルをスキャン中",
    loadError: "Specを読み込めません",
    noSpecsTitle: "Specが見つかりません",
    noSpecsDescription:
      "このワークスペースには設定済みのSpecファイルがまだありません。",
    refresh: "Specツリーを再読み込み",
    tree: "Specツリー",
  },
  markdown: {
    chooseSpec: "Specを選択",
    chooseFile: "ファイルを選択",
    idleDescription:
      "ワークスペースを開いてMarkdownファイルを選ぶと読み始められます。",
    loading: "Markdownを読み込み中",
    loadError: "Markdownを読み込めません",
    missingTitle: "ファイルが見つかりません",
    missingDescription: "このワークスペースでは利用できません。",
    emptyTitle: "ファイルは空です",
    reload: "Markdownを再読み込み",
    renderedDocument: "レンダリング済みMarkdownドキュメント",
  },
} as const;
