//! Comment JSON persistence format.
//!
//! The canonical file shape is a wrapper object:
//!
//! ```json
//! {
//!   "version": 2,
//!   "comments": []
//! }
//! ```
//!
//! The wrapper and every current field are required. Legacy arrays, v1
//! documents, and the retired resolved field are rejected. Timestamps are
//! generated by Rust application/domain code before conversion.

use std::str::FromStr;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use thiserror::Error;

use crate::domain::{
    comment::{
        BlockIndex, BlockType, CharRange, Comment, CommentAnchor, CommentBody, CommentDomainError,
        CommentId, CommentScope, CommentStatus, ScopedComments, ScopedCommentsError, TextHash,
        TextSnippet,
    },
    spec::SpecFileKey,
};

const COMMENT_JSON_VERSION: u32 = 2;

pub fn serialize_comments(comments: &ScopedComments) -> Result<String, CommentJsonError> {
    let document = CommentJsonDocument::from_domain(comments.comments());

    serde_json::to_string_pretty(&document).map_err(CommentJsonError::Serialize)
}

pub fn deserialize_comments(
    scope: CommentScope,
    contents: &str,
) -> Result<ScopedComments, CommentJsonError> {
    let document = CommentJsonDocument::parse(contents)?;

    document.into_domain(scope)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct CommentJsonDocument {
    version: u32,
    comments: Vec<CommentRecordDto>,
}

impl CommentJsonDocument {
    fn from_domain(comments: &[Comment]) -> Self {
        let comments = comments
            .iter()
            .map(CommentRecordDto::from_domain)
            .collect::<Vec<_>>();

        Self {
            version: COMMENT_JSON_VERSION,
            comments,
        }
    }

    fn parse(contents: &str) -> Result<Self, CommentJsonError> {
        let document: Self =
            serde_json::from_str(contents).map_err(CommentJsonError::MalformedJson)?;

        if document.version != COMMENT_JSON_VERSION {
            return Err(CommentJsonError::UnsupportedVersion {
                version: document.version,
            });
        }

        Ok(document)
    }

    fn into_domain(self, scope: CommentScope) -> Result<ScopedComments, CommentJsonError> {
        let file_key = scope.file_key();
        let comments = self
            .comments
            .into_iter()
            .map(|comment| comment.into_domain(file_key))
            .collect::<Result<Vec<_>, _>>()?;

        ScopedComments::restore(scope, comments).map_err(CommentJsonError::Aggregate)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CommentRecordDto {
    id: String,
    anchor: CommentAnchorDto,
    body: String,
    status: String,
    created_at: DateTime<Utc>,
    updated_at: DateTime<Utc>,
    #[serde(flatten)]
    extra: Map<String, Value>,
}

impl CommentRecordDto {
    fn from_domain(comment: &Comment) -> Self {
        let anchor = CommentAnchorDto::from_domain(comment.anchor());

        Self {
            id: comment.id().as_str().to_string(),
            anchor,
            body: comment.body().as_str().to_string(),
            status: comment_status_to_json(comment.status()).to_string(),
            created_at: comment.created_at(),
            updated_at: comment.updated_at(),
            extra: Map::new(),
        }
    }

    fn into_domain(self, file_key: SpecFileKey) -> Result<Comment, CommentJsonError> {
        if self.extra.contains_key("resolved") {
            return Err(CommentJsonError::RetiredField { field: "resolved" });
        }

        Comment::restore(
            CommentId::new(self.id).map_err(CommentJsonError::Domain)?,
            self.anchor.into_domain(file_key)?,
            CommentBody::new(self.body).map_err(CommentJsonError::Domain)?,
            comment_status_from_json(&self.status)?,
            self.created_at,
            self.updated_at,
        )
        .map_err(CommentJsonError::Domain)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct CommentAnchorDto {
    block_type: String,
    block_index: usize,
    text_hash: String,
    text_snippet: String,
    char_offset: [usize; 2],
}

impl CommentAnchorDto {
    fn from_domain(anchor: &CommentAnchor) -> Self {
        let char_range = anchor.char_range();

        Self {
            block_type: block_type_to_json(anchor.block_type()).to_string(),
            block_index: anchor.block_index().value(),
            text_hash: anchor.text_hash().as_str().to_string(),
            text_snippet: anchor.text_snippet().as_str().to_string(),
            char_offset: [char_range.start(), char_range.end()],
        }
    }

    fn into_domain(self, file_key: SpecFileKey) -> Result<CommentAnchor, CommentJsonError> {
        Ok(CommentAnchor::new(
            file_key,
            block_type_from_json(&self.block_type)?,
            BlockIndex::new(self.block_index),
            TextHash::new(self.text_hash).map_err(CommentJsonError::Domain)?,
            TextSnippet::new(self.text_snippet).map_err(CommentJsonError::Domain)?,
            CharRange::new(self.char_offset[0], self.char_offset[1])
                .map_err(CommentJsonError::Domain)?,
        ))
    }
}

#[derive(Debug, Error)]
pub enum CommentJsonError {
    #[error("comment JSON is malformed")]
    MalformedJson(serde_json::Error),
    #[error("failed to serialize comment JSON")]
    Serialize(serde_json::Error),
    #[error("unsupported comment JSON version: {version}")]
    UnsupportedVersion { version: u32 },
    #[error("unsupported comment status: {status}")]
    UnsupportedStatus { status: String },
    #[error("retired comment JSON field is not accepted: {field}")]
    RetiredField { field: &'static str },
    #[error("unsupported comment anchor block type: {block_type}")]
    UnsupportedBlockType { block_type: String },
    #[error("comment JSON contains invalid domain data")]
    Domain(CommentDomainError),
    #[error("comment JSON violates scoped comment invariants: {0}")]
    Aggregate(ScopedCommentsError),
}

fn comment_status_to_json(status: CommentStatus) -> &'static str {
    match status {
        CommentStatus::Open => "open",
        CommentStatus::Resolved => "resolved",
    }
}

fn comment_status_from_json(status: &str) -> Result<CommentStatus, CommentJsonError> {
    match status {
        "open" => Ok(CommentStatus::Open),
        "resolved" => Ok(CommentStatus::Resolved),
        _ => Err(CommentJsonError::UnsupportedStatus {
            status: status.to_string(),
        }),
    }
}

fn block_type_to_json(block_type: BlockType) -> &'static str {
    match block_type {
        BlockType::Paragraph => "paragraph",
        BlockType::Heading => "heading",
        BlockType::ListItem => "list_item",
        BlockType::CodeBlock => "code_block",
        BlockType::BlockQuote => "block_quote",
        BlockType::Table => "table",
        BlockType::ThematicBreak => "thematic_break",
        BlockType::Html => "html",
        BlockType::Other => "other",
    }
}

fn block_type_from_json(block_type: &str) -> Result<BlockType, CommentJsonError> {
    match block_type {
        "paragraph" => Ok(BlockType::Paragraph),
        "heading" => Ok(BlockType::Heading),
        "list_item" => Ok(BlockType::ListItem),
        "code_block" => Ok(BlockType::CodeBlock),
        "block_quote" => Ok(BlockType::BlockQuote),
        "table" => Ok(BlockType::Table),
        "thematic_break" => Ok(BlockType::ThematicBreak),
        "html" => Ok(BlockType::Html),
        "other" => Ok(BlockType::Other),
        _ => Err(CommentJsonError::UnsupportedBlockType {
            block_type: block_type.to_string(),
        }),
    }
}

impl FromStr for CommentJsonDocument {
    type Err = CommentJsonError;

    fn from_str(contents: &str) -> Result<Self, Self::Err> {
        Self::parse(contents)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::spec::SpecId;

    fn timestamp(second: u32) -> DateTime<Utc> {
        DateTime::parse_from_rfc3339(&format!("2026-05-05T10:00:{second:02}Z"))
            .expect("timestamp should parse")
            .with_timezone(&Utc)
    }

    fn comment(id: &str, file_key: SpecFileKey, block_type: BlockType, resolved: bool) -> Comment {
        let status = if resolved {
            CommentStatus::Resolved
        } else {
            CommentStatus::Open
        };

        Comment::restore(
            CommentId::new(id).expect("comment id should be valid"),
            CommentAnchor::new(
                file_key,
                block_type,
                BlockIndex::new(3),
                TextHash::new("sha256_prefix_8chars").expect("hash should be valid"),
                TextSnippet::new("JWT token").expect("snippet should be valid"),
                CharRange::new(12, 24).expect("range should be valid"),
            ),
            CommentBody::new("Define refresh token expiry").expect("body should be valid"),
            status,
            timestamp(0),
            timestamp(1),
        )
        .expect("comment should be valid")
    }

    fn scope(file_key: SpecFileKey) -> CommentScope {
        CommentScope::new(
            SpecId::new("auth-flow").expect("spec id should be valid"),
            file_key,
        )
    }

    fn deserialize_for_file(
        file_key: SpecFileKey,
        contents: &str,
    ) -> Result<ScopedComments, CommentJsonError> {
        deserialize_comments(scope(file_key), contents)
    }

    #[test]
    fn serialize_comments_uses_versioned_wrapper_and_stable_field_names() {
        let comments = ScopedComments::restore(
            scope(SpecFileKey::Impl),
            vec![comment(
                "cmt_1a2b3c",
                SpecFileKey::Impl,
                BlockType::Paragraph,
                false,
            )],
        )
        .expect("aggregate should restore");
        let json = serialize_comments(&comments).expect("comments should serialize");
        let value: serde_json::Value =
            serde_json::from_str(&json).expect("serialized JSON should parse");

        assert_eq!(serde_json::json!(2), value["version"]);
        assert!(value["comments"].is_array());
        assert_eq!(serde_json::json!("cmt_1a2b3c"), value["comments"][0]["id"]);
        assert!(value["comments"][0]["anchor"].is_object());
        assert_eq!(
            serde_json::json!("Define refresh token expiry"),
            value["comments"][0]["body"]
        );
        assert_eq!(serde_json::json!("open"), value["comments"][0]["status"]);
        assert!(value["comments"][0].get("resolved").is_none());
        assert_eq!(
            serde_json::json!("2026-05-05T10:00:00Z"),
            value["comments"][0]["createdAt"]
        );
        assert_eq!(
            serde_json::json!("2026-05-05T10:00:01Z"),
            value["comments"][0]["updatedAt"]
        );
    }

    #[test]
    fn deserialize_comments_round_trips_domain_comments() {
        let scope = scope(SpecFileKey::Impl);
        let expected = ScopedComments::restore(
            scope.clone(),
            vec![
                comment("cmt_open", SpecFileKey::Impl, BlockType::Paragraph, false),
                comment(
                    "cmt_resolved",
                    SpecFileKey::Impl,
                    BlockType::CodeBlock,
                    true,
                ),
            ],
        )
        .expect("aggregate should restore");
        let json = serialize_comments(&expected).expect("comments should serialize");

        let actual = deserialize_comments(scope, &json).expect("comments should deserialize");

        assert_eq!(expected, actual);
    }

    #[test]
    fn deserialize_comments_rejects_malformed_json() {
        let result = deserialize_for_file(SpecFileKey::Impl, "{");

        assert!(matches!(result, Err(CommentJsonError::MalformedJson(_))));
    }

    #[test]
    fn deserialize_comments_rejects_unsupported_version() {
        let result = deserialize_for_file(SpecFileKey::Impl, r#"{"version":1,"comments":[]}"#);

        assert!(matches!(
            result,
            Err(CommentJsonError::UnsupportedVersion { version: 1 })
        ));
    }

    #[test]
    fn deserialize_comments_rejects_unknown_block_type() {
        let json = r#"
{
  "version": 2,
  "comments": [
    {
      "id": "cmt_bad_block",
      "anchor": {
        "blockType": "image",
        "blockIndex": 3,
        "textHash": "sha256_prefix_8chars",
        "textSnippet": "JWT token",
        "charOffset": [12, 24]
      },
      "body": "Define refresh token expiry",
      "status": "open",
      "createdAt": "2026-05-05T10:00:00Z",
      "updatedAt": "2026-05-05T10:00:01Z"
    }
  ]
}
"#;

        let result = deserialize_for_file(SpecFileKey::Impl, json);

        assert!(matches!(
            result,
            Err(CommentJsonError::UnsupportedBlockType { block_type })
                if block_type == "image"
        ));
    }

    #[test]
    fn deserialize_comments_rejects_invalid_domain_values() {
        let json = r#"
{
  "version": 2,
  "comments": [
    {
      "id": "cmt_bad_range",
      "anchor": {
        "blockType": "paragraph",
        "blockIndex": 3,
        "textHash": "sha256_prefix_8chars",
        "textSnippet": "JWT token",
        "charOffset": [24, 12]
      },
      "body": "Define refresh token expiry",
      "status": "open",
      "createdAt": "2026-05-05T10:00:00Z",
      "updatedAt": "2026-05-05T10:00:01Z"
    }
  ]
}
"#;

        let result = deserialize_for_file(SpecFileKey::Impl, json);

        assert!(matches!(
            result,
            Err(CommentJsonError::Domain(
                CommentDomainError::InvalidCharRange { start: 24, end: 12 }
            ))
        ));
    }
    #[test]
    fn deserialize_comments_rejects_legacy_array() {
        let result = deserialize_for_file(SpecFileKey::Impl, "[]");

        assert!(matches!(result, Err(CommentJsonError::MalformedJson(_))));
    }

    #[test]
    fn deserialize_comments_requires_current_wrapper_fields() {
        for json in [r#"{}"#, r#"{"version":2}"#, r#"{"comments":[]}"#] {
            let result = deserialize_for_file(SpecFileKey::Impl, json);

            assert!(matches!(result, Err(CommentJsonError::MalformedJson(_))));
        }
    }

    #[test]
    fn deserialize_comments_requires_status() {
        let json = r#"
{
  "version": 2,
  "comments": [{
    "id": "cmt_missing_status",
    "anchor": {
      "blockType": "paragraph",
      "blockIndex": 3,
      "textHash": "sha256_prefix_8chars",
      "textSnippet": "JWT token",
      "charOffset": [12, 24]
    },
    "body": "Define refresh token expiry",
    "createdAt": "2026-05-05T10:00:00Z",
    "updatedAt": "2026-05-05T10:00:01Z"
  }]
}
"#;

        let result = deserialize_for_file(SpecFileKey::Impl, json);

        assert!(matches!(result, Err(CommentJsonError::MalformedJson(_))));
    }

    #[test]
    fn deserialize_comments_rejects_retired_resolved_field() {
        let json = r#"
{
  "version": 2,
  "comments": [{
    "id": "cmt_retired",
    "anchor": {
      "blockType": "paragraph",
      "blockIndex": 3,
      "textHash": "sha256_prefix_8chars",
      "textSnippet": "JWT token",
      "charOffset": [12, 24]
    },
    "body": "Define refresh token expiry",
    "status": "open",
    "resolved": false,
    "createdAt": "2026-05-05T10:00:00Z",
    "updatedAt": "2026-05-05T10:00:01Z"
  }]
}
"#;

        let result = deserialize_for_file(SpecFileKey::Impl, json);

        assert!(matches!(
            result,
            Err(CommentJsonError::RetiredField { field: "resolved" })
        ));
    }
}
